version: "3.7"

services: 
  node:
    build:
      context: ./config/node
      args:
        NODE_VERSION: ${NODE_VERSION}
        TZ: "$TZ"  
    container_name: node
    restart: always
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
    tty: true
    # stdin_open: true
    networks:
      - default

  nginx:
    build:
      context: ./config/nginx 
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TZ: "$TZ"  
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw # rw 读写(read and write)
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:rw # ro 只读(readonly) 只能看不能动
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    depends_on:
      - php
    networks:
      - default

  php:
    build:
      context: ./config/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php.sh
        TZ: "$TZ"
    container_name: php
    ports:
      - "${PHP_HOST_PORT}:9000"
    restart: always
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.conf:rw
      - ${PHP_FPMD_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
    networks:
      - default

  mysql:
    build:
      context: ./config/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        TZ: "$TZ"
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default

  redis:
    build:
      context: ./config/redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
        TZ: "$TZ"
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${REDIS_LOG_DIR}:/var/log/redis
      - ${REDIS_DATA_DIR}:/data
    restart: always
    networks:
      - default

  elasticsearch:
    build:
      context: ./config/elasticsearch
    container_name: elasticsearch
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
    volumes:
      - ${ELASTICSEARCH_DATA_DIR}:/usr/share/elasticsearch/data
      - ./config/elasticsearch/analysis/:/usr/share/elasticsearch/config/analysis
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=fate-cluster
      - node.name=fate-node
      - cluster.initial_master_nodes=fate-node  # 不设置会报错 Exit 78 
    depends_on:
      - php
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge 
